FROM grafana/grafana:13.1.0

COPY grafana/files/dashboard.yaml /etc/grafana/provisioning/dashboards/tc35.yaml
COPY grafana/files/datasource.yaml /etc/grafana/provisioning/datasources/tc35.yaml
COPY grafana/files/dashboards/ /etc/grafana/tc35-dashboards/
