FROM docker.elastic.co/elasticsearch/elasticsearch:8.19.19

ENV discovery.type=single-node
ENV xpack.security.transport.ssl.enabled=false
ENV xpack.security.http.ssl.enabled=false
ENV xpack.security.enabled=false
EXPOSE 9200
